FROM ubuntu:16.04
MAINTAINER cocosbcx
RUN apt-get update && \
    apt-get install -y python3 \
                        python3-dev \
                        python3-pip \
    && apt-get clean \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* \
   && pip3 install tornado requests pymysql -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN mkdir -p /app
WORKDIR /app
EXPOSE 80
EXPOSE 443
CMD ["bash"]
